# Generated by Django 6.0.7 on 2026-07-28 15:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('hotel_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('LODGE', 'Lodge'), ('RESORT', 'Resort'), ('B&B', 'Bed & Breakfast'), ('GUESTHOUSE', 'Guesthouse'), ('CAMP', 'Camp')], default='HOTEL', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('zta_registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_approved_by_zta', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hotel', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='core.region')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='ZTAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='zta_reports/')),
                ('total_hotels', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating_national', models.FloatField(default=0.0)),
                ('regional_summary', models.JSONField(default=dict)),
                ('aspect_summary_national', models.JSONField(default=dict)),
                ('regional_service_gaps', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zta_reports', to='core.region')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('review_text', models.TextField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('platform', models.CharField(choices=[('TRIPADVISOR', 'TripAdvisor'), ('GOOGLE', 'Google Reviews'), ('BOOKING', 'Booking.com'), ('QR', 'QR Code Feedback'), ('MANUAL', 'Manual Entry')], default='QR', max_length=20)),
                ('platform_review_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_overall', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('sentiment_food', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('sentiment_accommodation', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('sentiment_staff_hospitality', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('sentiment_welcome_experience', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('sentiment_cleanliness', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('sentiment_value_for_money', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('sentiment_safety', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.hotel')),
            ],
            options={
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['hotel', 'review_date'], name='core_review_hotel_i_7aabbf_idx'), models.Index(fields=['platform'], name='core_review_platfor_0cf50c_idx'), models.Index(fields=['sentiment_overall'], name='core_review_sentime_8bb595_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('aspect_summary', models.JSONField(default=dict)),
                ('service_gaps', models.JSONField(default=dict)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.hotel')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('hotel', 'week_start')},
            },
        ),
    ]
